name: flutter_launcher_icons
description: A package which simplifies the task of updating your Flutter app's launcher icon.
version: 0.9.2
maintainer: Mark O'Sullivan (@MarkOSullivan94)
homepage: https://github.com/fluttercommunity/flutter_launcher_icons

dependencies:
  args: ^2.3.1
  image: ^3.1.3
  path: ^1.8.0
  yaml: ^3.1.1

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  test: ^1.17.11
